### ISSUE TITLE
《c++程序设计》谭浩强课后习题答案.txt里习题3.2求圆的体积出错

### ISSUE THREAD

**Issue by UryWu** [Flamealone/C-language-study#2]
[《c++程序设计》谭浩强课后习题答案.txt里习题3.2求圆的体积](https://github.com/FlameAlpha/cpp-language-study/blob/master/%E3%80%8Ac%2B%2B%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E3%80%8B%E8%B0%AD%E6%B5%A9%E5%BC%BA%E8%AF%BE%E5%90%8E%E4%B9%A0%E9%A2%98%E7%AD%94%E6%A1%88.txt)
代码152行这里应该改为vq=4.0/3.0 * pi * r * r * r;

**Comment by FlameAlpha** [comment]
已修改
